# import pandas with shortcut 'pd'
import pandas as pd

# read_csv function which is used to read the required CSV file
#path = "D:\\Dot\\Dot EDI\\Truck 1.csv"
d = pd.read_csv("D:\\Dot\\Dot EDI\\Truck 1.csv")

# display
#print("Original 'Truck 1.csv' CSV Data: \n")
#print(d)

# pop function which is used in removing or deleting columns from the CSV files
d.drop(["Unnamed: 0", "SHIPMENT SHIPPED QTY", "QUANTITY ORD UOM", "QUANTITY SHIP UOM", "NET WEIGHT", "NET WEIGHT UOM", "CATCH WEIGHT FLAG", "EXPIRATION DATE", "LOT NUMBER", "PARTNER NUMBER", "DOT CUSTOMER NUMBER", "DOT CUSTOMER SHIPTO", "LOAD NUMBER", "SHIP NOTICE DATE", "SHIP NOTICE TIME", "SHIPPED DATE", "SHIPPED TIME", "DELIVERY DATE", "SHIP TO NAME", "SHIP TO ADDRESS", "SHIP TO CITY", "SHIP TO STATE", "SHIP TO ZIP CODE", "ISR NAME", "ISR PHONE", "ORDER NUMBER", "ORDER SEQUENCE NUMBER", "PO DATE", "SHIPMENT SHIPPED UOM", "SHIPMENT NET WEIGHT", "SHIPMENT NET WT UOM", "SHIPMENT GROSS WEIGHT", "SHIPMENT GROSS WT UOM", "SHIPMENT TOTAL CUBE", "SHIPMENT CUBE UOM", "SHIPMENT NUM PALLETS", "REFERENCE NUMBER", "MODE OF TRANSPORT", "ORDER SHIPPED QTY", "ORDER NET WEIGHT", "ORDER NET WT UOM", "ORDER GROSS WEIGHT", "ORDER GROSS WT UOM", "ORDER TOTAL CUBE", "ORDER TOTAL CUBE UOM", "ORDER NUM PALLETS", "PALLET TIERS", "PALLET BLOCKS", "PALLET HEIGHT", "PALLET HEIGHT UOM", "QUANTITY ON PALLET", "PALLET NET WEIGHT", "PALLET NET WEIGHT UOM", "PALLET GROSS WEIGHT", "PALLET GROSS WEIGHT UOM", "PALLET VOLUME", "PALLET VOLUME UOM", "UP UPC NUMBER", "UI UPC NUMBER", "HEIGHT", "HEIGHT UOM", "LENGTH", "LENGTH UOM", "WIDTH", "WIDTH UOM", "PACK", "SIZE", "PACK UOM", "GROSS WEIGHT", "GROSS WEIGHT UOM", "CODE DATE", "TOTAL CUBE", "CUBE UOM", "EACH FLAG", "OPERATOR ORDER NUMBER", "OPERATOR SEQUENCE NUMBER", "STORE NAME", "STORE NUMBER", "STORE DUNS NUMBER", "STORE ADDRESS", "STORE CITY", "STORE STATE", "STORE ZIP CODE"], axis=1, inplace=True)
d.drop(["REF NUMBER 1", "REF DESCRIPTION 1", "EXCHANGE ORDER NUMBER", "EXCHANGE SEQUENCE NUMBER", "REF QUALIFIER 1", "REF NUMBER 2", "REF NUMBER 3", "REF NUMBER 4", "REF NUMBER 5", "REF QUALIFIER 2", "REF QUALIFIER 3", "REF QUALIFIER 4", "REF QUALIFIER 5", "REF DESCRIPTION 2", "REF DESCRIPTION 3", "REF DESCRIPTION 4", "REF DESCRIPTION 5", "DETAIL REF NUMBER"], axis=1, inplace=True)
# display
#print("\nCSV Data after deleting the column 'year':\n")
#print(d)

d.to_csv("D:\\Dot\\Dot EDI\\Truck 1.csv")
